// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5clMxCrwIy_qeWPDjbKye2LN3n02aCKk',
    appId: '1:69738522756:web:117ccbcb8c5de83ebb7ad1',
    messagingSenderId: '69738522756',
    projectId: 'flutter-72d2a',
    authDomain: 'flutter-72d2a.firebaseapp.com',
    storageBucket: 'flutter-72d2a.appspot.com',
    measurementId: 'G-JZEFJY03SP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDYlAYFdgE9CI-ind5dv9gQmN4h9jOFmY',
    appId: '1:69738522756:android:26f782011aa16fcbbb7ad1',
    messagingSenderId: '69738522756',
    projectId: 'flutter-72d2a',
    storageBucket: 'flutter-72d2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfeDnqkcEI2kFtxf-Aq87ULg2AEFvqnd0',
    appId: '1:69738522756:ios:e1a70106ae560d2ebb7ad1',
    messagingSenderId: '69738522756',
    projectId: 'flutter-72d2a',
    storageBucket: 'flutter-72d2a.appspot.com',
    iosClientId: '69738522756-nvldh5dhiut5d26ntb54pkbj0hnbttdn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfeDnqkcEI2kFtxf-Aq87ULg2AEFvqnd0',
    appId: '1:69738522756:ios:7294ff8824826de0bb7ad1',
    messagingSenderId: '69738522756',
    projectId: 'flutter-72d2a',
    storageBucket: 'flutter-72d2a.appspot.com',
    iosClientId: '69738522756-vi044inpvra1tiuhjakoqd1qduqv4qhf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
